services:
  - type: web
    name: facebook-downloader-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    healthCheckIntervalSeconds: 30
    restartTimeoutSeconds: 30