services:
  - type: web
    name: facebook-downloader-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health
    healthCheckIntervalSeconds: 30
    restartTimeoutSeconds: 30